name: 'Jenkins Plugin Scan'
on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    set-plugins:
        runs-on: ubuntu-latest
        outputs:
            plugins: ${{steps.plugins.outputs.plugins}}
        steps:
            - name: Get plugins file
              uses: actions/checkout@v4
              with:
                sparse-checkout: |
                  plugins-list.txt
                sparse-checkout-cone-mode: false

            - name: Select random plugins
              id: plugins
              run: |
                apt update && apt install jq -y;
                out="[$(shuf -n 10 plugins-list.txt |sed 's/^/\"/;s/$/\"/g' |tr '\n' ','|sed 's/,$//g')]";
                echo "plugins=$(jq -cr '@json' <<< "$out")" >> $GITHUB_OUTPUT
              shell: bash

    scan-plugins:
        needs: set-plugins
        runs-on: ubuntu-latest
        strategy:
            matrix: 
                plugins: ${{ fromJSON(needs.set-plugins.outputs.plugins) }}
        steps:
            - name: Run Semgrep
              run: |
               apt update && apt install python3 python3-pip; pip3 install semgrep;
               git clone https://github.com/jenkinsci/${{matrix.plugins}}.git ${{runner.temp}}/${{matrix.plugins}}
               semgrep scan --config "p/java" --include "*.java" ${{runner.temp}}/${{matrix.plugins}} >> ${{runner.temp}}/${{matrix.plugins}}.semgrep.txt

            - name: Upload scan result
              uses: actions/upload-artifact@v4
              with:
                name: ${{matrix.plugins}}
                path: ${{runner.temp}}/${{matrix.plugins}}.semgrep.txt
